### ISSUE TITLE
Argument 1 passed to Symfony/component/process/process::_construct() must be of type array, string given

### ISSUE THREAD

**Issue by mhamaddarweesh0** [marellocommerce/marello-application#27] opened 2022-04-04 20:24 UTC
Hi,
I am installing marello on my ubunto 20.0.4 and while executing (`composer install`) I faced this error.
for the parameters they are requesting, must of them was the default options except[database_password, database_port] 
I am using:
1- Linux ubunto 20.0.4
2- composer 2.3.2
3- MySQL 8.0
4- Symfony 5.4.5
![Screenshot from 2022-04-04 01-31-49](https://user-images.githubusercontent.com/82947065/161625243-04aeccf3-b549-44bc-849e-4f9e0f3f0ca0.png)

**Comment by 24198** [comment] 2022-04-06 07:10
Hi @mhamaddarweesh0,

Can you share what version of Marello you are trying to install and the PHP version you're using?

Thanks!

**Comment by mhamaddarweesh0** [comment] 2022-04-06 08:37
Hi
I am using the latest version of marello with php 8.0
I solved the issue by making some changes ro the file permission handler.php
`
protected function getProcess($commandline){
if(is_array($commandline)
          return new Process($commandline);
$newcommandline = explode(" ", $commandline);
return new Process($newcommandline);
}
`
But I wanted to report the issue to make you know
Is there any better others solutions?
Thank you

**Comment by 24198** [comment] 2022-04-29 06:31
Hi @mhamaddarweesh0,

Sorry for the late response, I was able to reproduce the error and it seems like it's not related to PHP itself, but rather the `composer` version. Since composer 2.3.x it has been giving issues with the install on Marello and PHP 8.0, with Oro not adhering to the stricter standard of creating a new process. The easies way to resolve the issue at the moment is by reverting to a composer version < 2.3.x using `composer self-update --2.2` which will downgrade the composer version and you'll be able to install the application without issues.

Regarding the platform, there is currently a fix committed on the 4.2 branch of Oro, but it has not been released at the time of writing see [Permission Handler Fix](https://github.com/oroinc/platform/commit/697b00c794a2f7885140f065323c3515f6077b0d).

Thank you for reporting, once the fix has been included in a release, we'll be able to update our platform and version to.

Kind Regards,

Jaimy

**Closed** 2022-06-15 13:19 UTC
